apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configurations:
- kustomizeconfig.yaml
resources:
- PersistentVolume-juicefs.yaml
- PersistentVolumeClaim-juicefs.yaml
- StorageClass-juicefs.yaml
patchesStrategicMerge:
- pv-juicefs.yaml
secretGenerator:
- name: juicefs
vars:
- name: JUICEFS_SECRET
  objref:
    apiVersion: v1
    kind: Secret
    name: juicefs
- name: JUICEFS_SECRET_NAMESPACE
  objref:
    apiVersion: v1
    kind: Secret
    name: juicefs
  fieldRef:
    fieldpath: metadata.namespace
