apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juicefs-csi-demo
bases:
configurations:
- kustomizeconfig.yaml
resources:
- StorageClass-juicefs.yaml
- PersistentVolume-juicefs-csi-demo.yaml
- demo-app.yaml
secretGenerator:
- name: juicefs-auth-csi-demo
  env: Secret-juicefs-auth-csi-demo.env
  type: Opaque
vars:
- name: JUICEFS_AUTH_SECRET_NAME
  objref:
    kind: Secret
    name: juicefs-auth-csi-demo
    apiVersion: v1
- name: JUICEFS_AUTH_SECRET_NAMESPACE
  objref:
    kind: Secret
    name: juicefs-auth-csi-demo
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
