apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juicefs-csi-demo
bases:
- base
secretGenerator:
- name: juicefs-csi-demo
  env: Secret-juicefs-csi-demo.env
  type: Opaque
  behavior: merge
