apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../../../deploy/volume
- ../../../deploy/pod
configMapGenerator:
- name: juicefs-vars
  literals:
  - JUICEFS_NAME=csi-demo
secretGenerator:
- name: juicefs
  env: Secret-juicefs.env
  type: Opaque
  behavior: merge
vars:
- name: JUICEFS_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: juicefs-vars
  fieldRef:
    fieldpath: data.JUICEFS_NAME

