apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../../deploy/volume
secretGenerator:
- name: juicefs
  env: Secret-juicefs-static.env
  type: Opaque
  behavior: merge
