apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juicefs-csi-demo
bases:
configurations:
- kustomizeconfig.yaml
resources:
- resources/StorageClass-juicefs.yaml
- resources/PersistentVolume-juicefs-csi-demo.yaml
- resources/PersistentVolumeClaim-juicefs-csi-demo.yaml
- resources/Pod-juicefs-app-1.yaml
- resources/Pod-juicefs-app-2.yaml
configMapGenerator:
- name: juicefs-vars
  literals:
  - JUICEFS_NAME=csi-demo
secretGenerator:
- name: juicefs-auth-csi-demo
  env: Secret-juicefs-auth-csi-demo.env
  type: Opaque
vars:
- name: JUICEFS_NAME
  objref:
    kind: ConfigMap
    name: juicefs-vars
    apiVersion: v1
  fieldref:
    fieldpath: data.JUICEFS_NAME
- name: JUICEFS_AUTH_SECRET_NAME
  objref:
    kind: Secret
    name: juicefs-auth-csi-demo
    apiVersion: v1
- name: JUICEFS_AUTH_SECRET_NAMESPACE
  objref:
    kind: Secret
    name: juicefs-auth-csi-demo
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
