apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    resources:
      requests:
        cpu: "0.1"
        memory: 16M
      limits:
        cpu: "1"
        memory: 1G
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: juicefs-csi-demo
