---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-csi-demo
spec:
  capacity:
    storage: 10Pi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs
  csi:
    driver: csi.juicefs.com
    volumeHandle: $(JUICEFS_NAME)
    fsType: juicefs
    nodePublishSecretRef:
      name: $(JUICEFS_SECRET_NAME)
      namespace: $(JUICEFS_SECRET_NAMESPACE)

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-csi-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: juicefs
  resources:
    requests:
      storage: 10Pi

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: juicefs
provisioner: csi.juicefs.com

---
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: juicefs-csi-demo
