apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
configurations:
- kustomizeconfig.yaml
resources:
- juicefs-static.yaml
configMapGenerator:
- name: juicefs-csi-demo-vars
  literals:
  - JUICEFS_NAME=csi-demo
vars:
- name: JUICEFS_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: juicefs-csi-demo-vars
  fieldref:
    fieldpath: data.JUICEFS_NAME
- name: JUICEFS_SECRET_NAME
  objref:
    kind: Secret
    name: juicefs-csi-demo
    apiVersion: v1
- name: JUICEFS_SECRET_NAMESPACE
  objref:
    kind: Secret
    name: juicefs-csi-demo
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
