apiVersion: apps/v1
kind: Deployment
metadata:
  name:  juicefs-csi-scaling
spec:
  selector:
    matchLabels:
      app: juicefs-csi-scaling
  template:
    metadata:
      labels:
        app: juicefs-csi-scaling
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out-$(POD).txt; sleep 5; done"]
        env:
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "20m"
            memory: "55M"
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: juicefs
