apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.1.0
          args:
            - --provisioner=csi.juicefs.com
            - --csi-address=$(ADDRESS)
            - --timeout=60s
            - --v=5
