apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../../deploy/volume
resources:
- pod.yaml
patchesStrategicMerge:
- pv-juicefs.yaml
secretGenerator:
- name: juicefs
  env: Secret-juicefs.env
  type: Opaque
  behavior: merge
