apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../../deploy/volume
- ../../deploy/pod
patchesStrategicMerge:
- pv-juicefs-mountOptions.yaml
secretGenerator:
- name: juicefs
  env: Secret-juicefs.env
  type: Opaque
  behavior: merge
