apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: juicefs-csi-demo
bases:
- ../../deploy/volume
secretGenerator:
- name: juicefs-csi-demo
  env: Secret-juicefs-csi-demo.env
  type: Opaque
  behavior: merge
configMapGenerator:
- name: juicefs-volume-vars
  literals:
  - JUICEFS_NAME=csi-demo
