name: Build juicefs image

on:
  workflow_dispatch:
  push:
    branches:
      - docker_build

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      run: docker login --username juicefs --password ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Buildx and Push docker image nightly
      run: |
        make juicefs-image-nightly-buildx
